### PR TITLE
[PR]: Update Ubuntu image in Terraform configuration file

### PR DESCRIPTION
**Pull request by MarcinP1304**
Description:
This pull request updates the Ubuntu image in the Terraform configuration file to version 20.04. The current image is outdated and not available in the GCP registry, causing errors during infrastructure deployment.

Proposed Changes:
Update the Ubuntu image resource in the Terraform configuration file to version 20.04.
Remove the outdated image reference.
Add the new image reference with the appropriate version and release date.

Steps to Test:
Clone the repository.
Checkout the branch with this pull request.
Run the Terraform configuration file using the command "deploystack install".
Verify that the infrastructure deployment completes successfully without any errors.

Expected Behavior:
After merging this pull request and running the updated Terraform configuration file, the infrastructure deployment should run smoothly on GCP.

Additional Information:
I've singed a contributor agreement. This update ensures that the Terraform configuration file is compatible with the official tutorial and keeps the infrastructure up to date. Thank you for your attention to this matter.

Please review and merge this pull request. Thank you!

### CODE REVIEW

**Comment by tpryan** [comment]
Wow, this is great. Let me just run the integration tests.

**Comment by MarcinP1304** [comment]
Of course, you are welcome to test it. I've tested it too, but you never know how it works in different environments.

**Comment by MarcinP1304** [comment]
Could you please merge this pull request?

**Comment by MarcinP1304** [comment]
Thank you, Ryan!

**Pull request merged**
